package taiCrypto

var SymmetricCryptoType uint8
var AsymmetricCryptoType = ASYMMETRICCRYPTOECDSA
var HashCryptoType = HASHCRYPTOHAS3
var CAAsymmetricCryptoType = CAASYMMETRICCRYPTOECDSA
var CertType uint8

const (
	SYMMETRICCRYPTOSM4      = 1
	SYMMETRICCRYPTOAES      = 2
	ASYMMETRICCRYPTOECDSA   = 3
	ASYMMETRICCRYPTOSM2     = 4
	ASYMMETRICCRYPTOECIES   = 5
	HASHCRYPTOSM3           = 6
	HASHCRYPTOHAS3          = 7
	CAASYMMETRICCRYPTOECDSA = 8
	CAASYMMETRICCRYPTOSM2   = 9
	CERTGM                  = 10
	CERTECDSA               = 11
)
